// Genre taxonomy mirrored from DistroKid's release-upload genre list, so a genre
// chosen in ArtistOps lines up with what the artist picks at their distributor.
// Source: DistroKid new-release form `genre1` dropdown.
export const DISTROKID_GENRES: string[] = [
  "Afrobeat",
  "Afropop",
  "Alternative",
  "Big Band",
  "Blues",
  "Children's Music",
  "Christian/Gospel",
  "Classical",
  "Comedy",
  "Contemporary Latin",
  "Country",
  "Dance",
  "Electronic",
  "Fitness & Workout",
  "Folk",
  "French Pop",
  "German Folk",
  "German Pop",
  "Hip Hop/Rap",
  "Holiday",
  "J-Pop",
  "Jazz",
  "K-Pop",
  "Latin",
  "Latin House",
  "Latin Jazz",
  "Latin Urban",
  "Maskandi",
  "Metal",
  "New Age",
  "Pop",
  "Pop in Spanish",
  "Punk",
  "R&B/Soul",
  "Reggae",
  "Rock",
  "Rock en Español",
  "Singer/Songwriter",
  "Soundtrack",
  "Spoken Word",
  "Vocal",
  "World",
  "Xigaza",
];
