export const mockSongs = [
  {
    id: '1',
    title: 'Midnight Drive',
    artist: 'Alex Rivera',
    writers: ['Alex Rivera', 'Maya Chen'],
    publishers: ['Sunset Music Publishing'],
    splits: [{ name: 'Alex Rivera', percentage: 60 }, { name: 'Maya Chen', percentage: 40 }],
    isrc: 'USRC12345678',
    upc: '123456789012',
    releaseDate: '2024-03-15',
    genre: 'Pop',
    bpm: 128,
    key: 'C Major',
    status: 'MONETIZED',
    createdAt: '2024-01-10',
  },
  {
    id: '2',
    title: 'Golden Hours',
    artist: 'Alex Rivera',
    writers: ['Alex Rivera'],
    publishers: ['Sunset Music Publishing'],
    splits: [{ name: 'Alex Rivera', percentage: 100 }],
    isrc: 'USRC12345679',
    upc: '123456789013',
    releaseDate: '2024-05-20',
    genre: 'R&B',
    bpm: 95,
    key: 'F Minor',
    status: 'RELEASED',
    createdAt: '2024-02-15',
  },
  {
    id: '3',
    title: 'Electric Soul',
    artist: 'Alex Rivera',
    writers: ['Alex Rivera', 'Jordan Blake', 'Sam Torres'],
    publishers: ['Sunset Music Publishing', 'Nova Sound'],
    splits: [{ name: 'Alex Rivera', percentage: 50 }, { name: 'Jordan Blake', percentage: 30 }, { name: 'Sam Torres', percentage: 20 }],
    isrc: 'USRC12345680',
    upc: '123456789014',
    releaseDate: null,
    genre: 'Electronic',
    bpm: 140,
    key: 'A Minor',
    status: 'MASTERED',
    createdAt: '2024-03-01',
  },
  {
    id: '4',
    title: 'Sunrise Boulevard',
    artist: 'Alex Rivera',
    writers: ['Alex Rivera', 'Maya Chen'],
    publishers: ['Sunset Music Publishing'],
    splits: [{ name: 'Alex Rivera', percentage: 70 }, { name: 'Maya Chen', percentage: 30 }],
    isrc: null,
    upc: null,
    releaseDate: null,
    genre: 'Indie Pop',
    bpm: 112,
    key: 'G Major',
    status: 'MIXED',
    createdAt: '2024-04-10',
  },
  {
    id: '5',
    title: 'Neon Nights',
    artist: 'Alex Rivera',
    writers: ['Alex Rivera'],
    publishers: ['Sunset Music Publishing'],
    splits: [{ name: 'Alex Rivera', percentage: 100 }],
    isrc: null,
    upc: null,
    releaseDate: null,
    genre: 'Synthwave',
    bpm: 118,
    key: 'D Minor',
    status: 'DEMO',
    createdAt: '2024-05-01',
  },
];

export const mockCopyrights = [
  {
    id: '1',
    songId: '1',
    songTitle: 'Midnight Drive',
    registrationNumber: 'PAu004123456',
    filingDate: '2024-01-20',
    claimant: 'Alex Rivera',
    authors: ['Alex Rivera', 'Maya Chen'],
    workType: 'Musical Work',
    registeredWithUSCO: true,
    registeredWithPRO: true,
    registeredWithMLC: true,
    registeredWithSX: false,
    registeredWithDist: true,
    proName: 'ASCAP',
  },
  {
    id: '2',
    songId: '2',
    songTitle: 'Golden Hours',
    registrationNumber: 'PAu004123457',
    filingDate: '2024-03-10',
    claimant: 'Alex Rivera',
    authors: ['Alex Rivera'],
    workType: 'Musical Work',
    registeredWithUSCO: true,
    registeredWithPRO: true,
    registeredWithMLC: true,
    registeredWithSX: true,
    registeredWithDist: true,
    proName: 'ASCAP',
  },
  {
    id: '3',
    songId: '3',
    songTitle: 'Electric Soul',
    registrationNumber: null,
    filingDate: null,
    claimant: 'Alex Rivera',
    authors: ['Alex Rivera', 'Jordan Blake', 'Sam Torres'],
    workType: 'Musical Work',
    registeredWithUSCO: false,
    registeredWithPRO: false,
    registeredWithMLC: false,
    registeredWithSX: false,
    registeredWithDist: false,
    proName: null,
  },
];

export const mockDistributors = [
  {
    id: '1',
    name: 'DistroKid',
    accountId: 'DK-ARivera-2023',
    email: 'support@distrokid.com',
    website: 'https://distrokid.com',
    notes: 'Primary distributor. Annual plan.',
    activeSongs: 2,
    totalRevenue: 4821.50,
  },
  {
    id: '2',
    name: 'CD Baby',
    accountId: 'CDB-98234',
    email: 'support@cdbaby.com',
    website: 'https://cdbaby.com',
    notes: 'Used for older catalog.',
    activeSongs: 1,
    totalRevenue: 1203.75,
  },
  {
    id: '3',
    name: 'TuneCore',
    accountId: 'TC-Alex2021',
    email: 'support@tunecore.com',
    website: 'https://tunecore.com',
    notes: 'Backup distributor for select releases.',
    activeSongs: 0,
    totalRevenue: 342.20,
  },
];

export const mockDistributions = [
  {
    id: '1',
    songId: '1',
    songTitle: 'Midnight Drive',
    distributorId: '1',
    distributorName: 'DistroKid',
    upc: '123456789012',
    isrc: 'USRC12345678',
    stores: ['Spotify', 'Apple Music', 'Amazon Music', 'YouTube Music', 'Tidal'],
    status: 'ACTIVE',
    releaseDate: '2024-03-15',
  },
  {
    id: '2',
    songId: '2',
    songTitle: 'Golden Hours',
    distributorId: '1',
    distributorName: 'DistroKid',
    upc: '123456789013',
    isrc: 'USRC12345679',
    stores: ['Spotify', 'Apple Music', 'Amazon Music', 'YouTube Music'],
    status: 'ACTIVE',
    releaseDate: '2024-05-20',
  },
  {
    id: '3',
    songId: '1',
    songTitle: 'Midnight Drive',
    distributorId: '2',
    distributorName: 'CD Baby',
    upc: '123456789012',
    isrc: 'USRC12345678',
    stores: ['Spotify', 'Apple Music'],
    status: 'TAKEN_DOWN',
    releaseDate: '2023-06-01',
    takedownDate: '2024-01-01',
  },
];

export const mockRevenue = [
  { id: '1', songTitle: 'Midnight Drive', platform: 'Spotify', revenueType: 'STREAMING', amount: 1243.50, period: '2024-05-01', currency: 'USD' },
  { id: '2', songTitle: 'Midnight Drive', platform: 'Apple Music', revenueType: 'STREAMING', amount: 892.20, period: '2024-05-01', currency: 'USD' },
  { id: '3', songTitle: 'Golden Hours', platform: 'Spotify', revenueType: 'STREAMING', amount: 567.80, period: '2024-05-01', currency: 'USD' },
  { id: '4', songTitle: 'Midnight Drive', platform: 'ASCAP', revenueType: 'PRO_ROYALTY', amount: 420.00, period: '2024-04-01', currency: 'USD' },
  { id: '5', songTitle: 'Golden Hours', platform: 'YouTube', revenueType: 'YOUTUBE_CONTENT_ID', amount: 312.40, period: '2024-05-01', currency: 'USD' },
  { id: '6', songTitle: 'Midnight Drive', platform: 'MLC', revenueType: 'MECHANICAL', amount: 188.90, period: '2024-03-01', currency: 'USD' },
  { id: '7', songTitle: 'Midnight Drive', platform: 'TikTok', revenueType: 'TIKTOK', amount: 98.75, period: '2024-05-01', currency: 'USD' },
  { id: '8', songTitle: 'Golden Hours', platform: 'Apple Music', revenueType: 'STREAMING', amount: 445.60, period: '2024-05-01', currency: 'USD' },
  { id: '9', songTitle: 'Midnight Drive', platform: 'SoundExchange', revenueType: 'SOUND_EXCHANGE', amount: 652.30, period: '2024-04-01', currency: 'USD' },
  { id: '10', songTitle: 'Midnight Drive', platform: 'Sync License', revenueType: 'SYNC_LICENSE', amount: 2500.00, period: '2024-02-01', currency: 'USD' },
];

export const mockStreamPlays = [
  { id: '1', songTitle: 'Midnight Drive', platform: 'Spotify', plays: 245320, period: '2024-05-01', isrc: 'USRC12345678' },
  { id: '2', songTitle: 'Midnight Drive', platform: 'Apple Music', plays: 89430, period: '2024-05-01', isrc: 'USRC12345678' },
  { id: '3', songTitle: 'Midnight Drive', platform: 'YouTube Music', plays: 34210, period: '2024-05-01', isrc: 'USRC12345678' },
  { id: '4', songTitle: 'Golden Hours', platform: 'Spotify', plays: 123450, period: '2024-05-01', isrc: 'USRC12345679' },
  { id: '5', songTitle: 'Golden Hours', platform: 'Apple Music', plays: 45670, period: '2024-05-01', isrc: 'USRC12345679' },
  { id: '6', songTitle: 'Midnight Drive', platform: 'TikTok', plays: 892100, period: '2024-05-01', isrc: 'USRC12345678' },
  { id: '7', songTitle: 'Midnight Drive', platform: 'Spotify', plays: 198340, period: '2024-04-01', isrc: 'USRC12345678' },
  { id: '8', songTitle: 'Golden Hours', platform: 'TikTok', plays: 234500, period: '2024-05-01', isrc: 'USRC12345679' },
];

export const mockSocialPosts = [
  { id: '1', songTitle: 'Midnight Drive', platform: 'Instagram', status: 'POSTED', caption: 'New single out now! 🎵 #MidnightDrive', hashtags: ['MidnightDrive', 'NewMusic', 'Pop'], scheduledAt: null, postedAt: '2024-03-15', campaign: 'Release Campaign' },
  { id: '2', songTitle: 'Midnight Drive', platform: 'TikTok', status: 'BOOSTED', caption: 'POV: driving at midnight to this song...', hashtags: ['MidnightDrive', 'AlexRivera', 'FYP'], scheduledAt: null, postedAt: '2024-03-16', campaign: 'Release Campaign' },
  { id: '3', songTitle: 'Golden Hours', platform: 'Facebook', status: 'SCHEDULED', caption: 'Something golden is coming...', hashtags: ['GoldenHours', 'ComingSoon'], scheduledAt: '2024-05-18', postedAt: null, campaign: 'Pre-Release' },
  { id: '4', songTitle: 'Golden Hours', platform: 'Instagram', status: 'DRAFTED', caption: 'Golden Hours is almost here', hashtags: ['GoldenHours', 'AlexRivera'], scheduledAt: null, postedAt: null, campaign: 'Pre-Release' },
  { id: '5', songTitle: 'Electric Soul', platform: 'YouTube', status: 'IDEA', caption: 'Behind the scenes of making Electric Soul', hashtags: ['BehindTheScenes', 'ElectricSoul'], scheduledAt: null, postedAt: null, campaign: null },
  { id: '6', songTitle: 'Midnight Drive', platform: 'X', status: 'COMPLETED', caption: 'Midnight Drive just hit 1M streams!', hashtags: ['MidnightDrive', 'Milestone'], scheduledAt: null, postedAt: '2024-04-20', campaign: null },
];

export const mockAdCampaigns = [
  {
    id: '1',
    name: 'Midnight Drive - Release Push',
    songTitle: 'Midnight Drive',
    platform: 'Meta',
    objective: 'Stream Conversion',
    budget: 500,
    startDate: '2024-03-15',
    endDate: '2024-03-31',
    targetAudience: '18-34, Pop fans, US/UK/CA',
    status: 'COMPLETED',
    impressions: 245000,
    clicks: 12300,
    ctr: 5.02,
    cpc: 0.041,
    conversions: 892,
    costPerConv: 0.56,
    revenueAttributed: 1240.50,
  },
  {
    id: '2',
    name: 'Golden Hours - Pre-Save',
    songTitle: 'Golden Hours',
    platform: 'Meta',
    objective: 'Pre-Save Clicks',
    budget: 300,
    startDate: '2024-05-10',
    endDate: '2024-05-20',
    targetAudience: '18-45, R&B fans, US',
    status: 'ACTIVE',
    impressions: 89400,
    clicks: 4210,
    ctr: 4.71,
    cpc: 0.071,
    conversions: 312,
    costPerConv: 0.96,
    revenueAttributed: null,
  },
  {
    id: '3',
    name: 'TikTok Boost - Midnight Drive',
    songTitle: 'Midnight Drive',
    platform: 'TikTok',
    objective: 'Awareness',
    budget: 200,
    startDate: '2024-04-01',
    endDate: '2024-04-15',
    targetAudience: '16-30, Music fans',
    status: 'COMPLETED',
    impressions: 892100,
    clicks: 45200,
    ctr: 5.07,
    cpc: 0.0044,
    conversions: null,
    costPerConv: null,
    revenueAttributed: 98.75,
  },
  {
    id: '4',
    name: 'Electric Soul - Hype Campaign',
    songTitle: 'Electric Soul',
    platform: 'Google/YouTube',
    objective: 'YouTube Views',
    budget: 400,
    startDate: null,
    endDate: null,
    targetAudience: 'Electronic fans, 18-40',
    status: 'DRAFT',
    impressions: null,
    clicks: null,
    ctr: null,
    cpc: null,
    conversions: null,
    costPerConv: null,
    revenueAttributed: null,
  },
];

export const mockPixelEvents = [
  { id: '1', songTitle: 'Midnight Drive', visitorId: 'v_abc123', pageUrl: '/midnight-drive', referrer: 'https://instagram.com', eventType: 'page_view', utmSource: 'instagram', utmMedium: 'social', utmCampaign: 'release-push', createdAt: '2024-05-20T14:23:11Z' },
  { id: '2', songTitle: 'Midnight Drive', visitorId: 'v_abc123', pageUrl: '/midnight-drive', referrer: null, eventType: 'play_button', utmSource: 'instagram', utmMedium: 'social', utmCampaign: 'release-push', createdAt: '2024-05-20T14:23:45Z' },
  { id: '3', songTitle: 'Midnight Drive', visitorId: 'v_def456', pageUrl: '/midnight-drive', referrer: 'https://tiktok.com', eventType: 'page_view', utmSource: 'tiktok', utmMedium: 'social', utmCampaign: 'tiktok-boost', createdAt: '2024-05-20T15:10:22Z' },
  { id: '4', songTitle: 'Midnight Drive', visitorId: 'v_def456', pageUrl: '/midnight-drive', referrer: null, eventType: 'email_signup', utmSource: 'tiktok', utmMedium: 'social', utmCampaign: 'tiktok-boost', createdAt: '2024-05-20T15:11:05Z' },
  { id: '5', songTitle: 'Golden Hours', visitorId: 'v_ghi789', pageUrl: '/golden-hours', referrer: 'https://facebook.com', eventType: 'pre_save', utmSource: 'facebook', utmMedium: 'paid', utmCampaign: 'pre-save', createdAt: '2024-05-21T09:34:18Z' },
  { id: '6', songTitle: 'Midnight Drive', visitorId: 'v_jkl012', pageUrl: '/midnight-drive', referrer: 'https://google.com', eventType: 'merch_click', utmSource: 'google', utmMedium: 'organic', utmCampaign: null, createdAt: '2024-05-21T11:22:44Z' },
];

export const mockContacts = [
  { id: '1', name: 'Marcus Thompson', role: 'producer', email: 'marcus@studiox.com', phone: '+1-310-555-0101', company: 'Studio X Productions', website: 'https://studiox.com', notes: 'Produced Midnight Drive and Golden Hours', tags: ['producer', 'mix', 'trusted'] },
  { id: '2', name: 'Maya Chen', role: 'co-writer', email: 'maya@mayachenmusic.com', phone: '+1-212-555-0182', company: null, website: 'https://mayachenmusic.com', notes: 'Co-wrote Midnight Drive. 40% split.', tags: ['co-writer', 'pop'] },
  { id: '3', name: 'Jordan Blake', role: 'co-writer', email: 'jordan@blakebeats.com', phone: null, company: 'Blake Beats LLC', website: null, notes: 'Co-wrote Electric Soul. 30% split.', tags: ['co-writer', 'electronic'] },
  { id: '4', name: 'Sarah Williams', role: 'sync_agent', email: 'sarah@syncbridge.com', phone: '+1-424-555-0233', company: 'SyncBridge Agency', website: 'https://syncbridge.com', notes: 'Placed Midnight Drive in TV show. Commission: 20%', tags: ['sync', 'TV', 'film'] },
  { id: '5', name: 'David Park', role: 'curator', email: 'david@playlisthq.com', phone: null, company: 'PlaylistHQ', website: 'https://playlisthq.com', notes: 'Spotify playlist curator. Reach out 2 weeks before release.', tags: ['curator', 'spotify', 'playlisting'] },
  { id: '6', name: 'Sunset Music Publishing', role: 'publisher', email: 'admin@sunsetpub.com', phone: '+1-310-555-0199', company: 'Sunset Music Publishing', website: 'https://sunsetpub.com', notes: 'Primary publisher. 15% admin fee.', tags: ['publisher', 'admin'] },
  { id: '7', name: 'TechnoVision Media', role: 'video_creator', email: 'hello@technovision.tv', phone: null, company: 'TechnoVision Media', website: 'https://technovision.tv', notes: 'Created music video for Midnight Drive.', tags: ['video', 'visual'] },
];

export const dashboardStats = {
  totalSongs: 5,
  releasedSongs: 2,
  registeredCopyrights: 2,
  totalRevenue: 7321.45,
  monthlyRevenue: 3559.95,
  activeCampaigns: 1,
  websiteConversions: 5,
  monthlyData: [
    { month: 'Jan', revenue: 420 },
    { month: 'Feb', revenue: 2920 },
    { month: 'Mar', revenue: 1243 },
    { month: 'Apr', revenue: 1072 },
    { month: 'May', revenue: 3560 },
  ],
  topSongsByRevenue: [
    { title: 'Midnight Drive', revenue: 6095.65, streams: 1459700 },
    { title: 'Golden Hours', revenue: 1225.80, streams: 403620 },
  ],
  topPlatformsByPlays: [
    { platform: 'TikTok', plays: 1126600 },
    { platform: 'Spotify', plays: 567110 },
    { platform: 'Apple Music', plays: 135100 },
    { platform: 'YouTube Music', plays: 34210 },
  ],
};
